### ISSUE TITLE
NixOS package

### ISSUE THREAD

**Issue by MichaelBrunn3r** [Souravgoswami/oreo-cursors#3]
Hi, I'm currently writing a NixOS package for this project. I got the original oreo-cursors from varlesh working. But now I see that there is a fork that has vastly more features and is much more recent. I would rather make a package for this project.

Are you now the maintainer of this project? Or is this just your features on top of the original?
If you are now the original maintainer, I would just use the name 'oreo-cursors' as the package name. Otherwise 'oreo-cursors-souravgoswami' could be an option.

Also, would be it be possible to use Git Tags for new releases? I'm currently basing versions of the date of the latest commit, but I never know if the latest commit is stable. Adding version tags would help me out a bunch :)

**Comment by Souravgoswami** [comment]
Hi @MichaelBrunn3r,

Thank you so much for considering the Oreo cursor for NixOS! It's heartening to know, and personally, I'm quite excited about the idea of it being packaged for NixOS.

To address your second question, yes, I'm currently maintaining this project. While the frequency of issues has been low, I do periodically make updates, especially when I find the time and inspiration to add new themes.

The reason my repository appears more updated than the original is due to some of my PRs not being approved on the original project. That said, I assure you, the updates and changes I've incorporated into my version are stable. I take care to ensure everything on the master branch is well-tested before it's pushed.

Regarding naming, while I appreciate the consideration of adding my name as a suffix, I believe for the ease of users, a more descriptive or memorable name might be beneficial. Perhaps something along the lines of "oreo-cursor-extras" or "oreo-cursor-extended" would be both memorable and indicative of the additional features?

Lastly, I truly appreciate your suggestion regarding git tags. It makes sense, and I'll definitely implement the use of tags for new releases moving forward.

Thanks again for all your efforts. Please don't hesitate to reach out if there's anything you'd like to discuss or if you have further questions!

**Comment by MichaelBrunn3r** [comment]
Thanks a lot for the quick help.
I created a [pull request](https://github.com/NixOS/nixpkgs/pull/258995) to add the package.
Good point on the package name, I hope `oreo-cursors-plus` is acceptable :)

Love the work that you are doing. The size and border color made my switch to the white version possible :D

**Comment by MichaelBrunn3r** [comment]
🥳 NixOS package is now accepted and waiting for backport. I will post again and close this commit once it is available.
I accidentally left the PR unatended because I didn't know they were waiting for me to make some changes 😅.

[Original PR](https://github.com/NixOS/nixpkgs/pull/258995) (merged)
[Backport PR](https://github.com/NixOS/nixpkgs/pull/281838)

**Comment by Souravgoswami** [comment]
Wow! It's a really amazing news! Thank you so much for including my oreo-cursors mod in NixOS!

**Comment by MichaelBrunn3r** [comment]
Finally, the package is now available on the `23.11` channel ([link](https://search.nixos.org/packages?channel=23.11&show=oreo-cursors-plus&from=0&size=50&sort=relevance&type=packages&query=oreo)).

There is nothing left to do other than updating it if there are any updates to this project, so I'm closing this issue. Thanks for the help publishing it.
